Repository ceph/ceph.io, pull requests merged in 2021-06, with the labels that each got.

#143 news/index.html: add subscribe link
  src/en/news/index.html
Labels: ceph.io, documentation

#144 ceph.io/roadmap: cleaning up roadmap
  src/en/developers/roadmap/index.md
Labels: ceph.io, documentation

#146 ceph.io/developers: rewriting marketing copy 1
  src/en/developers/index.html
Labels: ceph.io

#147 ceph.io/developers: update docs link
  src/en/developers/index.html
Labels: ceph.io

#152 ceph.io/contribute: add contribute video
  src/en/developers/contribute/index.html
Labels: ceph.io

#150 ceph.io/discover: change header text
  src/en/discover/index.html
Labels: ceph.io

#149 ceph.io/news: removing lorem ipsum
  src/en/news/index.html
Labels: ceph.io

#148 ceph.io/developers: rewrite "code" page
  src/en/developers/code/index.html
Labels: ceph.io

#155 ceph.io/community -- added c-users and c-announce
  src/en/community/connect/index.html
Labels: ceph.io

#163 ceph.io/community: add tech talks (1 of several)
  src/en/community/community.json
Labels: ceph.io

#169 ceph.io/users: add telemetry dashboard
  src/en/users/index.html
Labels: ceph.io

#175 doc/ceph.io: discover -> technology (1 of x)
  src/en/discover/technology/index.html
Labels: ceph.io

#177 doc/cephio: adding stack.png to discover -> tech
  src/assets/bitmaps/stack.png
  src/en/discover/technology/index.html
Labels: ceph.io

#197 Optimise search index
  scripts/search-index.js
  src/_11ty/filters/cleanSearchRaw.js
  src/_data/i18n/index.js
  src/_includes/layouts/_base.njk
  src/_includes/layouts/listing-blog-search.njk
  src/css/utilities.display.css
  src/en/news/blog/search-raw.html
  src/js/search-output.js
Labels: enhancement

#193 doc/cephio: add users->documentation
  src/en/users/documentation/index.html
Labels: ceph.io

#187 cephio/users->getting started
  src/en/users/getting-started/index.html
Labels: ceph.io

#234 doc/releases: correct "Anthony D'Atri" spelling
  src/en/news/blog/2021/v16-2-0-pacific-released/index.md
Labels: ceph.io
